alias gcu311="buc -s gc_github_user=benjaminblodgett311"
alias gcu256="buc -s gc_github_user=ben256dev"
alias cwd="cd ~/ben256"
alias cwm="cd /var/www/ben256"
alias cwc="cd /etc/nginx/sites-available"
alias c="clear"
alias cl="c;l"
alias tt="toggle_touchpad"
alias chatgpt="cd ~/.shellgpt/;source shellgpt/bin/activate"
alias cdl="source change_directory_and_list"
alias cppc="cppcheck --enable=all --suppress=missingIncludeSystem"
alias eb="ssh erik@ben256.com"
alias cr="claude --resume"
alias bb="ssh benjamin@160.2.105.118"
export ONYX="benjaminblodgett311@onyx.boisestate.edu"
alias onyx="ssh $ONYX"
